import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BaseLayout from "@/components/baseLayout";
import "@/public/css/style.css";
import Providers from "@/utils/provider";

const roboto = Roboto_Condensed({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <BaseLayout>{children}</BaseLayout>
        </Providers>
      </body>
    </html>
  );
}
