import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BaseLayout from "@/components/baseLayout";
import "@/public/css/bootstrap.min.css";
import "@/public/css/style.css";
import Providers from "@/utils/provider";
import ImportBsJS from "@/utils/importBsJS";

const openSans = Open_Sans({
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  return (
    <html lang="en">
      <ImportBsJS />
      <body className={openSans.className}>
        <Providers>
          <BaseLayout lng={lng}>{children}</BaseLayout>
        </Providers>
      </body>
    </html>
  );
}
